### ISSUE TITLE
Attemt to send order results in HTTP code 301

### ISSUE THREAD

**Issue by PunchyRascal** [heureka/overeno-zakazniky#13]
exception 'Heureka\ShopCertification\RequesterException' with message 'Request resulted in HTTP code '301'. Response result:
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>301 Moved Permanently</title>
</head><body>
<h1>Moved Permanently</h1>
<p>The document has moved <a href="http://api.heureka.cz/shop-certification/v2/order/log">here</a>.</p>
</body></html>
' in \vendor\heureka\overenozakazniky\src\ShopCertification\CurlRequester.php:61

**Comment by grongor** [comment]
That is strange ... I will look into it tomorrow morning.

**Comment by grongor** [comment]
I'm terribly sorry - there was a misconfiguration on our servers. It is fixed now. There are some other small glitches but there shouldn't prevent you from using the API (and it will get fixed during this day). Thank you for your report, have a nice day.
