### ISSUE TITLE
Request results in HTTP 400

### ISSUE THREAD

**Issue by PunchyRascal** [heureka/overeno-zakazniky#16]
> exception 'Heureka\ShopCertification\RequesterException' with message 'Request resulted in HTTP code '400'. Response result:
> {
>     "code": 400,
>     "message": "bad-request",
>     "description": "There is a problem with your request. Please see the documentation for details.",
>     "dataErrors": [
>         "Expected key \"productItemIds\" to be \"string[]\", \"array\" of value \"[3258]\" given."
>     ]
> }' in \vendor\heureka\overeno-zakazniky\src\ShopCertification\CurlRequester.php:61

**Comment by grongor** [comment]
I think this isn't an issue with the library - the error message clearly states what you are doing wrong.

**Comment by PunchyRascal** [comment]
Enlighten me please, because I don't get what's wrong.

**Comment by grongor** [comment]
Well you seem to be passing an integer instead of a string into `addProductItemId` method. But as I look on the implementation it's doing the casting automatically. As far as I can tell you know it looks like json_encode converts the string variable to integer. I will look into it.

**Comment by PunchyRascal** [comment]
Thanks, that's what I saw too. I am not even passing integer, but a string too.

**Comment by grongor** [comment]
Well then I definitely bet on the json_encode/json_decode functions ... give me a few minutes please ;-)

**Comment by grongor** [comment]
Funny thing ... sorry for the inconvenience, I hope you won't find any other bugs :) Thanks for your help!

Fixed by #17

**Comment by PunchyRascal** [comment]
Right. You're very quick. I suppose you will need to release this before it takes effect.

**Comment by grongor** [comment]
I already tagged the version so you can use it ;-) its v2.0.2

**Comment by PunchyRascal** [comment]
Ok. Thanks. I just tested it and it seems to work fine.

**Comment by grongor** [comment]
Nice! If you find anything else, feel free to create an issue again ;-) Good night.
