### ISSUE TITLE
The productItemId was already added

### ISSUE THREAD

**Issue by AntiCZ** [heureka/overeno-zakazniky#25]
Ahoj, 

je potreba vyhazovat DuplicateProductItemIdException? Ona to chyba byt nemusi. U nas na shopu se stava bezne, ze produkt je soucasti vice konfiguraci a tudiz se v kosiku vyskytuje vicekrat.

Nestacilo by nahradit za?

`if (array_search($productItemId, $this->productItemIds) === false) {`
`$this->productItemIds[] = $productItemId;`
`}`

Svym zpusobem se knihovna snazi o nechtenou validaci kosiku.

**Comment by vojtasvoboda** [comment]
Zrovna řeším to samé, v našem e-shopu lze jeden produkt koupit jako plnohodnotný produkt, ale i jako dárek s nulovou cenou. Tj. dvě položky objednávky, stejné productItemId, jiný název, jiná cena.

**Comment by MiroslavHlavka** [comment]
Ahoj v následujícím sprintu na to koukneme a probereme s týmem

**Comment by MiroslavHlavka** [comment]
Ahoj, za nás je to validní chování. Pokud pošlete více stejných produktů, tak se vždy vytvoří jen jeden k hodnocení pro uživatele. Tzn. i kdybychom tu exception smazali tak funkčnost bude stejná, jen to nebude transparentní (Vy pošlete 4 produkty. K nám se uloží jen 3 a vy se o tom nedozvíte). Takže ideálně výjimku odchytávat nebo neposílat duplicitní produkty.
