### ISSUE TITLE
Timeout for request

### ISSUE THREAD

**Issue by MichalSkoula** [heureka/overeno-zakazniky#31]
Is it / will be possible to set a timeout for request?

**Comment by LuKillman** [comment]
I also wanted to propose that since yesterday infinite timeout caused problems in our application so I created example PR https://github.com/heureka/overeno-zakazniky/pull/32.

**Comment by MiroslavHlavka** [comment]
You are right, we will add a timeout for our requests. Thank you for bringing up this issue :)

**Comment by MiroslavHlavka** [comment]
We created new tag v4.0.1 where timeouts are implemented
